### ISSUE TITLE
When will the hardware schematics be released?

### ISSUE THREAD

**Issue by nhadler** [linklayer/BLEKey#1]

**Comment by hajdbo** [comment]
KICAD schematics have been released, but there is a number of pictures of a v1.1. And Mark Baseggio published a tweet saying that there is a new version with working LED: https://twitter.com/markbaseggio/status/693089729139445760

**Comment by blark** [comment]
Coming very soon folks! And yes, Kicad schematics are in the repo in the /hardware directory.
