### ISSUE TITLE
Parts list?

### ISSUE THREAD

**Issue by Beaubasaur** [linklayer/BLEKey#3]
Hi,

I've been looking through the hardware files, but I can't find a list of the parts needed to build one of these.

I'm planning on printing a PCB from the gerbs, but if you could provide a parts list I can hopefully get to hacking my company's door lock (for purely legit reasons).

Best Regards,
James Forbes

**Comment by gyaresu** [comment]
Page 10: https://www.blackhat.com/docs/us-15/materials/us-15-Evenchick-Breaking-Access-Controls-With-BLEKey-wp.pdf

**Comment by hajdbo** [comment]
| Designators | Mfr. | Part Number | Supplier P/N | Description | Qty. |
| --- | --- | --- | --- | --- | --- |
| K1 | AVX | 9176003022006 | 478­-4619-­1-­ND | IDC Connector | 1 |
| U1 | Raytac | MDBT40 | MDBT40 | Bluetooth Module (nRF51822) | 1 |
| Q1, Q2 | Diodes Inc | 2N7002­-7­F | 2N7002­-FDICT­-ND | FET | 2 |
| R2, R4 | Panasonic | ERJ­-3GEYJ104V | P100KGCT-­ND | Res 100k | 2 |
| R3, R5 | Panasonic | ERJ­-3EKF9312V | P93.1KHCT-­ND | Res 93.1k | 2 |
| R1 | Panasonic | ERJ­-3GEYJ221V | P220GCT-­ND | Res 220 | 1 |
| C1 | Murata | GRM188R71C104 KA01D | 490-­1532-­1­-ND | Cap 0.1 uF | 1 |
| C2, C3 | Murata | GRM1885C1H120 JA01D | 490-­1405-­1-­ND | Cap 12 pF | 2 |
| X1 | Epson | FC-135 32.7680KA-AC3 |  | 32.768 KHz Xtal 9pF | 1 |
| BATT1 | MPD | BU1632SM-­JJ-­GT | R BU1632SM-­JJ­-GCT-ND | Battery Holder | 1 |
| D1 | Lite­on | LTST-­C191KGKT | 160­-1446-­1-­ND | LED, Green | 1 |
| P1, P2 |  |  |  | 0.1" pin header (1x4) | 2 |

...and a CR1632 battery of course.
X1 should be 9pF according to MDBT40 reference circuit: http://www.raytac.com/download/MDBT40/MDBT40%20spec-Version%20A4.pdf

Also note that C1 is 1uF on the reference circuit, but 0.1uF on BLEkey. I guess both would work.

**Comment by blark** [comment]
We should probably put the whitepaper in the repo, and this info in the wiki. Thanks folks!
