### ISSUE TITLE
List of BLE Characteristics?

### ISSUE THREAD

**Issue by STFURTFMLAGG** [linklayer/BLEKey#5]

**Comment by ericevenchick** [comment]
Hey,

Yeah... We've had limited progress on the documentation here. I'm actually working on making the whole BLEKey process easier at the moment.

Really, I think documentation is in dire need, as Mark and I basically rushed to get this working for some talks.

**Comment by ChicoSlim** [comment]
How far are we from some documentation on using a mobile device? I am trying to convince my upper management that we need to upgrade all of our readers to OSDP and I can replay no problem just writing any badge I want to is the issue. They will not allow me to use a VM with Linux therefore I am stuck with the mobile app on my phone. Please reach out with some more info.

**Comment by STFURTFMLAGG** [comment]
Chico, look at the send_wiegand function of the firmware, it's really pretty easy to figure out from there.

You do understand that upgrading all of your readers to OSDP might be a difficult, and expensive task. Your access control system will have to have support for OSDP, and you would want to get readers that support the protocol natively, rather than a separate module that simply allows conversion from Weigand to OSDP over 485. Moreover, OSDP is not inherently secure. There are options. Make sure you are not convincing someone to spend money on another vulnerable solution.
